version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  backend:
    build: .
    container_name: django_app
    depends_on:
      - db
    volumes:
      - .:/app
      - ./static:/app/staticfiles
    env_file:
      - .env.prod
    command: ["/bin/bash", "/app/start.sh"]
    expose:
      - "8002"

volumes: 
  postgres_data:
