version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  backend:
    build: .
    container_name: django_app
    depends_on:
      - db
    volumes:
      - .:/app
      - ./static:/app/staticfiles
    env_file:
      - .env.prod
    command: ["/bin/bash", "/app/start.sh"]
    expose:
      - "8002"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
      - ./media:/app/media:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend

volumes: 
  postgres_data:
